### ISSUE TITLE
button convert

### ISSUE THREAD

**Issue by panikajo** [ThunbergOlle/colorvariables-preview-sourcemod#2]
button convert not working

**Comment by ThunbergOlle** [comment]
You shouldn't have to click convert in order for the text to display.
It was there for earlier test versions. Going to remove it in the next update! 👍

**Comment by ThunbergOlle** [comment]
Removed button. 🐤  Commit : https://github.com/ThunbergOlle/colorvariables-preview-sourcemod/commit/8fe60d70ace76b30d02d54325cc91c40ddb64a12

Closing this issue now! ⏱
