### ISSUE TITLE
bug symbols

### ISSUE THREAD

**Issue by panikajo** [ThunbergOlle/colorvariables-preview-sourcemod#3]
if i use --> it's not showing

**Comment by ThunbergOlle** [comment]
Hello 👋 

I'm not really sure what you want the previewer to do. Can you give me an example on the expected output. I'm not really used to coding with SourcePawn. (I'm pretty new) 

Thanks.

**Comment by panikajo** [comment]
add please this color
{DEFAULT}
{RED}
{LIGHTPURPLE}
{GREEN}
{LIME}
{LIGHTGREEN}
{LIGHTRED}
{GRAY}
{LIGHTOLIVE}
{OLIVE}
{PURPLE}
{LIGHTBLUE}
{BLUE}
![image](https://user-images.githubusercontent.com/4964185/50762655-3ec43e00-1276-11e9-98c3-f9317f6b5e41.png)

**Comment by ThunbergOlle** [comment]
Fixed this in version 1.1.2 (commit: https://github.com/ThunbergOlle/colorvariables-preview-sourcemod/commit/8fe60d70ace76b30d02d54325cc91c40ddb64a12 )

👍
